### ISSUE TITLE
工具: 代码循环复杂度统计工具

### ISSUE THREAD

**Issue by zoroqi** [phodal/awesome-modernization#1]
[terryyin/lizard](https://github.com/terryyin/lizard)这是一个分析代码[循环复杂度](https://zh.wikipedia.org/zh-hans/%E5%BE%AA%E7%92%B0%E8%A4%87%E9%9B%9C%E5%BA%A6)的工具.

它可以扫描出过于复杂的方法, 然后进一步分析, 看是否需要进行方法的拆解.

**Comment by phodal** [comment]
欢迎来 PR

**Comment by zoroqi** [comment]
已提交 #2
